print("FIND THE NUMBER OF SUBSET AND SUBSETS")
x=int(input("WRITE THE NUMBER OF ELEMENTS IN SET==="))
y=int(input("WRITE THE FIRST ELEMENT==="))
z=int(input("WRITE THE SECOND ELEMENT=== IF THE SET DOES NOT HAVE SECOND ELEMENT PRESS k"))
if z == '0':
    print(2)
